import { useEffect } from "react";
import { Link, useParams } from "wouter";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
import { engineeringNotes } from "@/lib/engineeringNotes";
import NotFound from "./NotFound";

const essays: Record<string, { heading: string; paragraphs: string[]; code?: string }[]> = {
  "valid-is-not-authorized": [
    { heading: "One call. Several different contracts.", paragraphs: ["Consider a tool that creates a support ticket. The payload can contain a valid title, a recognized priority, and every required field. That establishes that the request has the expected shape. It says nothing about whether this caller may create a ticket in the destination workspace—or whether a person has agreed to send the information there.", "ToolTrust makes these questions separately inspectable. Its replay models argument validation, permission checks, confirmation, and simulated execution. The useful result is not simply pass or fail. It is a trace that shows which boundary stopped the action and why."] },
    { heading: "Start with the schema, then keep going.", paragraphs: ["Checking that required keys exist misses a large part of a contract. A priority may be present but outside the supported enum. A nested field may have the wrong type. The current implementation uses a Draft 2020-12 JSON Schema validator so those constraints participate in the decision.", "Schema evaluation also needs a boundary. ToolTrust disables remote reference retrieval during validation. A submitted schema should not silently turn a local replay into an outbound network request. An unresolved reference becomes a visible validation failure; it is not treated as permission to continue."], code: '// Illustrative contract fragment\n{\n  "type": "object",\n  "properties": {\n    "priority": { "enum": ["low", "normal", "high"] }\n  },\n  "required": ["priority"]\n}' },
    { heading: "Permission and confirmation answer different questions.", paragraphs: ["A permission check asks whether the caller has the required capability. A confirmation step asks whether a particular action should proceed with these arguments and these consequences. Combining the two into a single boolean makes the explanation weaker: a reviewer cannot tell whether the caller lacked access or simply had not confirmed the proposed action.", "The lab therefore keeps the stages visible. A production design would bind permission evidence to an authenticated identity and bind confirmation to an exact operation. If the arguments change after review, the earlier approval should not silently apply to a different action. That binding is a production requirement, not a capability this simulation claims to implement."] },
    { heading: "Test the stop, not just the happy path.", paragraphs: ["The most useful regression cases here are calls that look nearly acceptable: a correct field name with an invalid value, an invalid nested object, or a remote schema reference. The tests inspect the validation outcome and whether execution was prevented. This gives the interface an honest reason to show a stopped trace.", "ToolTrust remains a deterministic design lab. It does not execute external tools or establish production identity. Its value is making a decision sequence concrete enough to review, test, and challenge before attaching real side effects."] },
  ],
  "webhooks-out-of-order": [
    { heading: "The transport is not the business timeline.", paragraphs: ["Imagine two events for the same order. The order was created at time 1000 and updated at time 1020, but the update reaches the receiver first. A receiver that blindly assigns the state of the latest arrival will move from updated back to created when the older event arrives.", "HookForge models that failure in a bounded, in-process simulation. The event trace lets a reviewer compare receiver capabilities under the same scenario. The interesting question is not whether every delivery was accepted. It is whether the final state still represents the newest accepted lifecycle event."] },
    { heading: "Duplicates and stale events are different failures.", paragraphs: ["A duplicate repeats an event identity. A stale event can have a completely different identity while describing an older point in the lifecycle. Deduplication alone will not catch that second case.", "The simulation keeps a set of accepted event IDs and separately tracks the latest accepted lifecycle timestamp. With ordering protection enabled, a lifecycle event older than that timestamp is rejected before it changes the summary state. The delivery remains visible in the trace, including the reason it was ignored."], code: '# Simplified ordering rule from the simulation\nif incoming_time < latest_state_time:\n    accept = False\n    reason = "preserve newer state"\n\n# Deduplication remains a separate decision.\nif event_id in seen_ids:\n    accept = False' },
    { heading: "A timestamp guard is a model, not a universal solution.", paragraphs: ["The lab uses a single synthetic order and a simple lifecycle. Real systems need to decide whether the provider supplies an authoritative sequence, version, or timestamp, and whether the event describes a transition or a complete resource snapshot. Equal timestamps and concurrent changes need explicit semantics. The lab's older-than check does not resolve every tie.", "In a production receiver, the decision and its state mutation would need to be atomic. Two workers must not both pass a duplicate check before either stores the event. External side effects need their own idempotency strategy, and raw delivery history needs durable storage. An in-memory set cannot prove any of those properties."] },
    { heading: "Make the failure explainable.", paragraphs: ["A rejected event can be a successful reliability outcome. HookForge records whether a delivery was accepted, whether it was a duplicate, and the notes explaining rejection. Unknown event types can be ignored when the receiver advertises that capability. Invalid signatures and malformed payloads are separate checks, so one protection is not mistaken for another.", "The regression test contrasts an unprotected receiver with an ordering-aware receiver. That comparison exposes the exact behavior the capability changes. It is more useful than a dashboard score by itself—and it leaves a clear next step for anyone extending the lab into a real receiver."] },
  ],
  "errors-that-explain": [
    { heading: "The response is part of the interface.", paragraphs: ["A developer reads an error while trying to do something else. They need to know what failed, whether changing the request could help, and what to try next. A generic invalid request message moves that work back to the person integrating the API.", "DX Orbit and DevStart approach the problem from complementary directions. DX Orbit inspects an OpenAPI document using explicit rules. DevStart gives a developer deterministic failure scenarios and recovery guidance. Neither measures real-world developer productivity; together they make contract quality and recovery behavior easier to discuss."] },
    { heading: "Give each part of the error a job.", paragraphs: ["A stable machine-readable code helps a client choose a recovery path. A field or location identifies the part of the request that needs attention. A message explains the constraint in language a person can understand. A next action suggests a correction without claiming that every failure is automatically recoverable.", "The example below is a proposed error shape, not a claim that every project emits this exact payload. Its purpose is to separate information that often gets compressed into one string."], code: '// Illustrative error contract\n{\n  "code": "INVALID_RETRY_COUNT",\n  "field": "max_retries",\n  "message": "Expected an integer retry count.",\n  "next_action": "Send a supported integer, not true or false."\n}' },
    { heading: "A small type detail can change the lesson.", paragraphs: ["In Python, a boolean is also an instance of int. A validation rule using isinstance(value, int) can therefore accept True where the scenario expects a retry count. DevStart uses an exact type check for that exercise and has a regression test for the boolean case.", "DX Orbit has a related boundary at upload and analysis time. Valid JSON does not guarantee a usable OpenAPI structure. The API now translates selected structural analysis failures into a 422 response and bounds uploaded input to two million bytes. These are practical guards, not a claim of complete OpenAPI conformance validation."] },
    { heading: "Measure what the exercise actually observes.", paragraphs: ["A training session can report whether an attempt succeeded and whether a later correction recovered. Those are facts about the submitted attempts in that session. They do not establish that onboarding is faster for a population of developers, or that a particular error message causes better outcomes.", "The same distinction applies to a contract score. An explicit rule can identify missing recovery information; it cannot observe a developer's confusion on its own. I use these tools to produce reviewable hypotheses and reproducible examples. Real usability conclusions would require research, instrumentation, and a defined comparison."] },
  ],
};

export default function EngineeringNotes() {
  const { slug } = useParams<{ slug?: string }>();
  const note = engineeringNotes.find(item => item.slug === slug);
  useEffect(() => {
    const previous = document.title;
    const description = document.querySelector<HTMLMetaElement>('meta[name="description"]');
    const previousDescription = description?.content;
    document.title = note ? `${note.title} — Amy Villa` : "Engineering Notes — Amy Villa";
    if (description) description.content = note?.summary ?? "Engineering notes by Amy Villa on tool validation, webhook reliability, and actionable API errors.";
    window.scrollTo(0, 0);
    return () => { document.title = previous; if (description && previousDescription !== undefined) description.content = previousDescription; };
  }, [note]);
  if (slug && !note) return <NotFound />;
  return <div className="engine-experience journal-page">
    <a href="#article-main" className="journal-skip">Skip to content</a>
    <header className="journal-nav"><Link href="/"><ArrowLeft size={15} /> AV / PORTFOLIO</Link><Link href="/notes">ENGINEERING NOTES</Link><a href="mailto:amyv.dev@gmail.com">LET’S TALK <ArrowUpRight size={15} /></a></header>
    <main id="article-main">
      <div className="journal-masthead"><p className="journal-kicker">AMY VILLA / FIELD NOTES / 2026</p><h1>{note ? note.title : <>Behind the work.<br /><em>Inside the decisions.</em></>}</h1><p className="journal-deck">{note ? note.summary : "Technical essays on the details that make automation understandable, APIs usable, and failure recoverable. Written around inspectable implementations."}</p></div>
      {!note ? <div className="journal-index">{engineeringNotes.map(item => <Link className="journal-entry" href={`/notes/${item.slug}`} key={item.slug}><span className="journal-number">{item.number}</span><div><p className="journal-kicker">{item.category} / {item.project}</p><h2>{item.title}</h2><p>{item.summary}</p></div><ArrowUpRight aria-hidden="true" /></Link>)}</div> : <>
        <div className="journal-byline"><span>BY AMY VILLA</span><span>07 OCTOBER 2026</span><span>IMPLEMENTATION NOTE / {note.number}</span></div>
        <div className="journal-layout"><aside className="journal-contents"><p className="journal-kicker">IN THIS NOTE</p><nav aria-label="Article contents">{essays[note.slug].map((section, i) => <a key={section.heading} href={`#section-${i}`}>{String(i + 1).padStart(2, "0")} / {section.heading}</a>)}</nav><a className="journal-source" href={`https://github.com/Amyvdev1/${note.repo}`} target="_blank" rel="noreferrer">INSPECT {note.repo.toUpperCase()} <ArrowUpRight size={15} /></a></aside>
        <article className="journal-body"><figure className="decision-flow"><figcaption>THE DECISION PATH / SIMPLIFIED</figcaption><ol>{note.diagram.map(step => <li key={step}>{step}</li>)}</ol></figure>{essays[note.slug].map((section, i) => <section id={`section-${i}`} key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map(text => <p key={text}>{text}</p>)}{section.code && <pre tabIndex={0} aria-label="Illustrative code example"><code>{section.code}</code></pre>}</section>)}<blockquote>{note.takeaway}</blockquote><div className="journal-evidence"><p className="journal-kicker">FOLLOW THE EVIDENCE</p><a href={`https://github.com/Amyvdev1/${note.repo}/blob/main/app/core.py`}>Implementation <ArrowUpRight size={14}/></a><a href={`https://github.com/Amyvdev1/${note.repo}/tree/main/tests`}>Regression tests <ArrowUpRight size={14}/></a>{note.repo === "dx-orbit" && <a href="https://github.com/Amyvdev1/devstart">DevStart source <ArrowUpRight size={14}/></a>}<p>Examples describe self-directed engineering labs. Production requirements are identified as future work, not claimed capabilities.</p></div></article></div>
        <section className="journal-next"><p className="journal-kicker">KEEP READING</p>{engineeringNotes.filter(item => item.slug !== note.slug).map(item => <Link key={item.slug} href={`/notes/${item.slug}`}>{item.title}<ArrowUpRight size={20}/></Link>)}</section>
      </>}
    </main><footer className="engine-footer"><span>© 2026 AMY VILLA</span><Link href="/">BACK TO THE WORK <ArrowUpRight size={14}/></Link></footer>
  </div>;
}
